name: windows_toast
description: A simple flutter package designed to display toast notifications in Windows applications.
version: 0.0.1
homepage: https://github.com/i-aiymen/windows_toast
repository: https://github.com/i-aiymen/windows_toast

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
